### ISSUE TITLE
Link incorreto no readme - SPRING BOOT uma aplicação completa | Como usar o docker

### ISSUE THREAD

**Issue by julianocanuto** [feltex/academicnet#5]
Fala amigo,

No arquivo readme, o link para o vídeo "*SPRING BOOT uma aplicação completa | Como usar o docker*", está apontando para o vídeo sobre deploy na AWS.

O link para o vídeo que fala do Docker é o: https://youtu.be/KynRfzk23Jc

**Comment by feltex** [comment]
Obrigado @julianocanuto,

    Atualizei o arquivo README.md. Fique a vontade para contrubuir. ;-)
